# Specify your preferred storage type
# Types of storage available: MySQL, SQLite, FlatFile
# When using SQLite or FlatFile, "database" will be the name of the file that the data is stored in
storage:
  type: SQLite
  database: data
  table_prefix: hoarder_
  address: ''
  username: ''
  password: ''

# If Hoarder should pay players for selling to it
# Economy providers: Vault, PlayerPoints
economy:
  enabled: true
  provider: Vault

#
event:
  # The amount of time, in minutes, the Hoarder event should last for
  timer-length: 240

  # The amount of winners and the amount of treasures given to them upon the Hoarder event ending.
  # Want to add more winners? Just add the spot that should win and the amount of treasures that should be given to them upon winning
  winners:
    1: 3 # First place gets 3 claimable Hoarder Treasures upon the event ending
    2: 2
    3: 1
    4: 1



use-material-list-as-blacklist: false

# Materials that the Hoarder can pick from and the price that they will pay for them
materials:
  diamond: 5
  white_wool: 4.72
  iron_ingot: 3.5