# Used for updating config on new releases. No need to change this
config-version: 1.0.4

# Language to use
lang: en_US

# Specify your preferred storage type
# Types of storage available: MySQL, SQLite, FlatFile
# When using SQLite or FlatFile, "database" will be the name of the file that the data is stored in
storage:
  type: SQLite
  database: data
  table_prefix: hoarder_
  address: ''
  username: ''
  password: ''


update-checking:
  enabled: true
  # If Hoarder should notify players with the 'hoarder.update' permission when an update is available
  notify-on-join: true

commands:
  # The default command action for /hoarder
  default-command-action: '[OPEN] guis/main.yml'
  # Aliases for the /hoarder command. Requires a restart to take effect
  command-aliases: []


# If Hoarder should pay players when selling items
# Economy providers: Vault, PlayerPoints
economy:
  enabled: true
  provider: Vault
  random-pricing:
    enabled: false
    min: 1.20
    max: 3.70


event:
  # The amount of time, in minutes, the Hoarder event should last for, set to 0 or lower to have Hoarder events only be started manually
  timer-length: 240
  # How often, in ticks, should Hoarder check to see if it has reached the specified timer-length
  # 20 ticks = 1 second. Changing this shouldn't be necessary. Recommended to leave at above at least 20 ticks (1 second)
  timer-check-interval: 600

  # Notify players if they won a Hoarder event or if they have prizes to claim upon joining the server
  notify-on-join: true
  # The amount of winners and the amount of treasures given to them upon the Hoarder event ending.
  # Want to add more winners? Just add the spot that should win and the amount of treasures that should be given to them upon winning
  winners:
    1: 3 # First place gets 3 claimable Hoarder Treasures upon the event ending
    2: 2
    3: 1
    4: 1


treasure-items:
  # All treasure items must have an identifier that correlates to their item and their % chance in our database
  # Change this value if you would like to ALWAYS set your identifiers manually and never have Hoarder automatically make identifiers.
  # Identifiers that are made by Hoarder will have this format: <Item_DisplayName>-<Amount>
  # Changing this to false will require you to specify your identifier when doing /hoarder treasure add <chance/weight> <identifier>

  # If you don't understand, then just leave this value to true
  auto-identifier: true

  # When determining a random item to give to a player upon claiming a treasure item, Hoarder uses
  # a weight system. Weights for each item are set when adding it to the treasure pool.
  # When giving a player an item, Hoarder creates a random number between 0 - <bound-int> and if
  # the random number is equal to or less than the weight of the item, then the item is given to the player.
  # Else, we move onto a different item and repeat the process.

  # This value is the bound integer that represents the highest number the random num could be.
  # Use this if you want to scale your weights to be higher or lower
  # Example: I want to scale my weights to be 0 - 1000 instead of 0 - 100
  bound-int: 100


gui-options:
  # Prevents items with the '[BACK_PAGE]' or '[NEXT_PAGE]' action from being placed in gui if the next/previous page does not exist
  hide-if-page-not-available: true


# Whether the materials list should act as a blacklist
# If using blacklist, Hoarder will randomly pick a material that is not in the blacklist
# If this setting is enabled, the 'random-pricing' setting will also automatically be enabled too
use-material-list-as-blacklist: false

# Materials that the Hoarder can pick from and the price that they will pay for them
# If economy is disabled, then the price will be ignored
materials:
  diamond: 5
  white_wool: 4.72
  iron_ingot: 3.51
  grass_block: 4.70
  oak_log: 3
  amethyst_shard: 2.50
  emerald: 7.30