name: Hoarder
version: '${version}'
main: dev.jsinco.hoarder.Hoarder
api-version: '1.20'
author: 'Jsinco'
description: 'Allows players to compete in Hoarding competitions and earn rewards!'
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
permissions:
  hoarder.command.treasure:
    description: 'Allows usage of /hoarder treasure. Used for adding, editing, and deleting treasures from storage'
    default: op
  hoarder.command.reload:
    description: 'Allows usage of /hoarder reload. Used for reloading the plugin''s config and storage'
    default: op
  hoarder.command.gui:
    description: 'Allows usage of /hoarder gui. Used for opening Hoarder GUIs'
    default: op
commands:
  hoarder:
    usage: '/hoarder <subcommand>?'
    description: 'Hoarder command'

