name: Hoarder
version: '${version}'
main: dev.jsinco.hoarder.Hoarder
api-version: '1.20'
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
permissions:
  hoarder.command.treasure:
    description: 'Allows usage of /hoarder treasure. Used for adding, editing, and deleting treasures from storage'
    default: op
  hoarder.command.reload:
    description: 'Allows usage of /hoarder reload. Used for reloading the plugin''s config and storage'
    default: op
commands:
  hoarder:
    description: 'Hoarder command'

