name: Hoarder
version: '${version}'
main: dev.jsinco.hoarder.Hoarder
api-version: '1.20'
author: 'Jsinco'
description: 'Allows players to compete in Hoarding competitions and earn rewards!'
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
  - DiscordSRV
permissions:
  hoarder.command.treasure:
    description: 'Allows usage of /hoarder treasure. Used for adding, editing, and deleting treasures from storage'
    default: op
  hoarder.command.reload:
    description: 'Allows usage of /hoarder reload. Used for reloading the plugin''s config and storage'
    default: op
  hoarder.command.gui:
    description: 'Allows usage of /hoarder gui. Used for opening Hoarder GUIs'
    default: op
  hoarder.command.claim:
    description: 'Allows usage of /hoarder claim. Used for claiming treasures from Hoarder'
    default: op
  hoarder.command.event:
    description: 'Allows usage of /hoarder event. Used for etc with Hoarder events'
    default: op
  hoarder.command.sell:
    description: 'Allows usage of /hoarder sell. Used for selling items to Hoarder'
    default: op
commands:
  hoarder:
    usage: '/hoarder <subcommand>?'
    description: 'Hoarder command'